( This gcode generated by /opt/eagle-5.6.0/ulp/pcb-gcode.ulp )
( Copyright 2005 by John Johnson. See readme.txt for licensing terms. )

( This file generated from the board /usr/data1/freebus/freebus-svn/freebus/trunk/hardware/Eagle Layouts/app_avr_glcd/glcd_240x128/glcd_240x128.brd )
( This file generated 05.03.10 21:20 )

( Settings from pcb-machine.h )
( tool size = 0.3000 )
( z high = 5.0000	z up = 2.0000	z down = -2.5000 )
( drill depth = -5.0000 )
( spindle on time = 1.0000 )
( milling depth = 5.0000 )
( tool change at X40.0000, Y-26.0000, Z5.0000 )
( feed rate = 200.0000	feed rate z = 40.0000 )

( Settings from pcb-defaults.h )
( Default isolate = 0.0025 )
( isolate max = 0.5588 )
( isolate step = 0.1500 )
( Generated: top outlines, top drill, bottom outlines, bottom drill,  )
( Unit of measure: mm )


G21

G90
G00 Z5.0000 
G00 X0 Y0
M03
G04 P1.000000
G01 X160.0000 Y0.0000 
G01 X160.0000 Y100.0000 
G01 X0.0000 Y100.0000 
G01 X0.0000 Y0.0000 
(File Footer)
G00 Z5.0000 
M05
M02
